### ISSUE TITLE
Unable to click on hyperlink within the pdf file

### ISSUE THREAD

**Issue by santosh5580** [webodf/ViewerJS#226]
Hi,

I am using ViewerJs to open pdf file, but unable to click on links within the pdf file.

http://www.webelement.cc/sebipages/ViewerJS/?zoom=page-width#http://www.webelement.cc/sebi_data/tenderfiles/jan-2017/1484650390871.pdf

**Comment by santosh5580** [comment]
Please provide if any solution.

**Comment by ilbonzo** [comment]
Do you have find solution to this problem?

**Comment by reginafcompton** [comment]
I encountered the same problem. I am a developer at DataMade, where I maintain https://boardagendas.metro.net (see source code at: [Github](https://github.com/datamade/la-metro-councilmatic)). We use `viewerjs` for rendering PDFs.

Some of the embedded PDFs do not have clickable hyperlinks, even though these links work on the PDFs themselves (e.g., https://boardagendas.metro.net/board-report/2018-0771/). The result looks like:

<img width="1272" alt="Screen Shot 2019-03-25 at 9 59 19 AM" src="https://user-images.githubusercontent.com/13078679/54925492-c79d5e00-4ee4-11e9-87dc-1d07d0769661.png">

This seems to be the result of `viewerjs` not correctly adding hyperlinks to the `annotationLayer`. For additional context, [we've described the problem here](https://github.com/datamade/la-metro-councilmatic/issues/294), as well.

**Comment by thz** [comment]
@reginafcompton you are actually not using webodf/ViewerJS but PDF.js directly.
